// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyySXCIXVhQlRbAae2Yefs332zcQ6313I',
    appId: '1:172876295788:web:8be9e891ce4284fd32f249',
    messagingSenderId: '172876295788',
    projectId: 'sdn-final-a2d81',
    authDomain: 'sdn-final-a2d81.firebaseapp.com',
    storageBucket: 'sdn-final-a2d81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX92WIFYi96HvOd08glfOKKhlr6aBzt2M',
    appId: '1:172876295788:android:5e379c6b1682153632f249',
    messagingSenderId: '172876295788',
    projectId: 'sdn-final-a2d81',
    storageBucket: 'sdn-final-a2d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRgEO3g_m6QIwlVK0SW3XtuTUgWStn5Y',
    appId: '1:172876295788:ios:d7eaa1242e6f34da32f249',
    messagingSenderId: '172876295788',
    projectId: 'sdn-final-a2d81',
    storageBucket: 'sdn-final-a2d81.appspot.com',
    androidClientId: '172876295788-a73nvdo17nsbbg1g7ruhsndohr13hk9p.apps.googleusercontent.com',
    iosClientId: '172876295788-d85d4vqg60jtn4mq4niule79v3q1vbv4.apps.googleusercontent.com',
    iosBundleId: 'com.SDN.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRgEO3g_m6QIwlVK0SW3XtuTUgWStn5Y',
    appId: '1:172876295788:ios:7742220df129580632f249',
    messagingSenderId: '172876295788',
    projectId: 'sdn-final-a2d81',
    storageBucket: 'sdn-final-a2d81.appspot.com',
    androidClientId: '172876295788-a73nvdo17nsbbg1g7ruhsndohr13hk9p.apps.googleusercontent.com',
    iosClientId: '172876295788-vjgfh1fc6nehoh9av73udnprkjt5srg9.apps.googleusercontent.com',
    iosBundleId: 'com.SDN.miniproject.RunnerTests',
  );
}
